# 講義 {.unnumbered}

本授業では、オペレーションズ・リサーチ（OR）の中の代表的な手法であるPERT、在庫理論、待ち行列理論、動的計画法、階層分析法、及び包絡分析法の数理を理解し、具体的な問題への応用を学ぶ。

## 講義情報

- 講義名：オペレーションズ・リサーチB
- 曜日：水曜日
- 時限：2時限目（10:50～12:30）
- 教室：西館 W202
- 担当教員：[劉 子昂](https://zi-ang-liu.github.io/)

## 到達目標

各分野について、下記の事項を目標して講義を行う。

- **PERT**の計算と解析方法を理解し、プロジェクトの評価を行うことができる。
- **在庫モデル**を理解し、自分で式を構築及び解析することができる。
- **待ち行列理論**の重要な式や定理を理論的に導出し、それらを適切に解釈することができる。
- **動的計画法**の基本的な考え方を理解し、簡単な問題への適用ができる。
- **階層分析法**による意思決定の手法を理解し、一対比較行列からウェイトと整合性を計算することができる。
- **包絡分析法**におけるCCRモデルを理解し、得られた結果を解釈することができる。

さらに、これらの手法を用いて比較的簡単な現象をモデル化し、解析することができる。

## ORの全体像


- 線形計画法
- 整数計画法
- 非線形計画法
- **動的計画法**
- グラフ理論・ネットワーク
- シミュレーション
- **在庫モデル**
- **待ち行列**
- **多基準意思決定分析**
- **プロジェクトマネジメント**
- ...

## ORは難しい？

### 基礎知識が必要

微分積分、線形代数、確率、統計の基礎知識が必要です。これらの基礎が不十分な場合、授業についていけないです。基礎知識が不十分な場合、必ず復習してください。

この講義では、以下の工夫をしています。

- 付録に私が書いた基礎知識のまとめがあります。随時更新しますので、参考にしてください。
- 講義資料には例題、図、演習問題を多く用意しています。
- プログラミングの実装例も示します。

### 数式が多い

ORは、問題を数理的にモデル化し、解析する学問です。数式をたくさん使い、証明も多いです。数式を読むのが苦手な人は、慣れるまで大変かもしれません。

この講義では、以下の工夫をしています。

- 証明は省略なく丁寧に行います。
- 私が推測したわかりにくいところをコラムで補足します。

## 何を学ぶ？

### モデル

### アルゴリズム

### 実装

## 授業時間外の学習

本授業の準備・復習等の授業時間外学習は、4時間を標準とする

## 必要なもの

- 本講義では，受講者自身のノートPCを用いて演習を行います．毎週必ずノートPCを持参してください．

## 私語

- 講義中の私語は厳禁です．
- 注意してもやめない場合は、減点を行います。

## 成績評価

- 期末試験（100%）
- 一回の欠席につき、10点減点。4回以上の欠席は単位取得不可。