---
title: 待ち行列とは
format:
  html:
    code-fold: true
jupyter: python3
---

## 待ち行列モデルの基本

待ち行列モデルを分類するのに，**ケンドールの記号**（Kendall's notation）を用いる。ケンドールの記号は，次の形式で表される。

$$
A/B/C
$$

ここで，$A$ は

$C$ はサーバ数を表す。

| 記号 | 意味 |
| ---- | ---- |
| $\lambda$ | 平均到着率，単位時間あたりの到着客数の平均|
| $\mu$ | 平均サービス率，単位時間あたりに処理できる客数の平均|
| $\rho$ | 利用率|
| $s$ | サーバ数 |

$1/\lambda$ は平均到着間隔，$1/\mu$ は平均サービス時間を表す．利用率 $\rho$ は，次の式で定義される．

$$
\rho = \frac{\lambda}{s \mu}
$$

:::{#exm-ice-cream}
あるアイスクリーム屋さんでは，1名の店員が客の注文を受け付け，アイスクリームを提供している．平均して，1時間に30人の客が来店している．店員は，1時間に60人の客に対応できる．このとき，平均到着率 $\lambda$ は30人/時間，平均サービス率 $\mu$ は60人/時間である．サーバ数 $s = 1$ であるため，利用率は

$$
\rho = \frac{30}{1 \times 60} = 0.5
$$
となる．また，1時間あたりの到着率が30人であるため，平均到着間隔は $1/\lambda = 1/30$ 時間，平均サービス時間は $1/\mu = 1/60$ 時間である．これを分単位で表すと，平均到着間隔は2分，平均サービス時間は1分となる．
:::

| 記号 | 意味 |
| ---- | ---- |
| $L$ | 平均系内客数 |
| $W$ | 平均滞在時間|
| $L_q$ | 平均待ち行列長 |
| $W_q$ | 平均待ち時間 |

**平均系内客数** $L$ は，待ち行列システム内にいる客数の平均を表す．**平均滞在時間** $W$ は，客がシステムに到着してサービスを受け，システムを退出するまでにかかる平均時間を表す．

**平均待ち行列長** $L_q$ は，待ち行列にいる客数の平均を表す．**平均待ち時間** $W_q$ は，客がシステムに到着してからサービスを受けるまでにかかる平均時間を表す．

**リトルの法則**（Little's Law）により，次の式が成り立つ．

$$
L = \lambda W
$$

$$
L_q = \lambda W_q
$$

さらに，平均滞在時間 $W$ は，平均待ち時間 $W_q$ と平均サービス時間 $1/\mu$ の和であるから，次の式で表される．

$$
W = W_q + \frac{1}{\mu}
$$

:::{#exm-bank}
ある銀行では，1時間に平均20人の客が来店し，各客が銀行に滞在する平均時間は12分である．このとき，平均系内客数 $L$ は

$$
L = \lambda W = 20 \times \frac{12}{60} = 4 \text{ 人}
$$

となる．つまり，銀行内には平均4人の客がいることになる．平均滞在時間 $W$ や平均到着率 $\lambda$ が増加すると，平均系内客数 $L$ も増加することがわかる．

さらに，平均サービス時間は6分であるとすると，平均待ち時間 $W_q$ と平均待ち行列長 $L_q$ はそれぞれ

$$
W_q = W - \frac{1}{\mu} = 12 - 6 = 6 \text{ 分}
$$

$$
L_q = \lambda W_q = 20 \times \frac{6}{60} = 2 \text{ 人}
$$

となる．つまり，客が行列で待つ平均時間は6分，1時間あたり平均2人の客が行列で待っていることになる．
:::

### 用語集

| 英語                    | 日本語       |
| ----------------------- | ------------ |
| service facility       | サービス施設 |
| server                 | サーバ     |
| number of servers      | サーバ数   |
| interarrival time      | 到着間隔   |
| service time           | サービス時間 |
